### ISSUE TITLE
Define names for all different edit interfaces

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#22]
Suggestions from Innsbruck are: 
Transcription interface: for the one Matti is developing (working title is line by line)
Proofread interface: for the first one of Nathanael
Correction interface: currently known as 'inverse Matti' 
Please add your comments.

**Comment by cziaarm** [comment]
We @hackmanschorsch @maxbry @jnphilipp think that the the current labels (Image, Line-by-Line, Side by Side and Text) are very close to what we should use because they describe the interface rather than tell one what to do with it. And the user will e.g. 'proof read' with probably more then one interface.

They can also be applied in "viewing mode" so we can toggle between editing and viewing, but retain the different methods of presentation.

**Comment by maxbry** [comment]
I think this issue should be moved to `test succeded` and if any user in unsatisfied with any of the four names, an issue can be created for renaming something. Otherwise this issue would stay open forever..
