### ISSUE TITLE
Change page status to toggle button

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-edit#58]
Checkbox for transcriber (Done, In Progress) and additional toggle box for editor to set to Final.

**Comment by jnphilipp** [comment]
Postponed until I can get user roles for a collection/document.

**Comment by cziaarm** [comment]
Tested as owner - select list: In Progress, Done, Final

Tested as editor - Toggle button: In progress, Done

Tested as Transcriber - edit button disabled

Tested as crowdTranscriber - Toggle button: In progress, Done

We should confirm whether the is the intended/agreed behaviour before setting this as Tests succeeded. Shouldn't an editor be able to set documents as done? A Transcriber user currently can't transcribe via the webUI, is this correct (possibly a matter of nomenclature)?

**Comment by GuenterMuehlberger** [comment]
Editor needs to be able to set to final

**Comment by hackmanschorsch** [comment]
Shouldn't have the transcriber the same rights as the crowdTranscriber: Toggle button: In progress, Done?
Btw: Now there is the possibiliy to get the collection metadata directly with one call:
https://transkribus.eu/TrpServerTesting/rest/collections/1/metadata (1 is collId)
For this week only on the test server!

**Comment by cziaarm** [comment]
I think so too.

Changes:

- [ ] Editor gets final
- [ ] Transcriber gets same permissions as CrowdTranscriber

@jnphilipp I am happy to step in on this if you are unable to find the time. Just let me know.

R

**Comment by cziaarm** [comment]
Just to check.. in 2f15d581addb25de5f927ceca96610741628572c I've ended up a making conditions like:

`if ( "{{ role }}" === "Editor" || "{{ role }}" === "Owner" || "{{ role }}" === "Admin" || "{{ role }}" === "CrowdTranscriber" || "{{ role }}" === "Transcriber" )`

If these are all the possible roles (?) I guess we can remove the condition altogether.

**Comment by hackmanschorsch** [comment]
Well, there is one left - the "Reader"

**Comment by cziaarm** [comment]
OK by the sounds of it the "Reader" has no edit permissions so the condition above would be suitable for the permission to edit (and indeed could be replaced by 

`if ( "{{r ole }}" !== "Reader" )`

But despite code efficiency this is now doing what we expect? @GuenterMuehlberger ?

**Comment by cziaarm** [comment]
Need to add the Transcriber to a condition on line 121 of edit/views.py

**Comment by EvaMLang** [comment]
Test results:

- [x] Reader: all editing buttons are disabled, no chance to save any transcript, no access to change status, behavior as expected according to role description
- [x] Transcriber: status changes are carried out immediately. Status does not change back from Done after new save is carried out. Any save activity triggers status "NEW" (instead of "IN_PROGRESS"), see screenshot below
![grafik](https://user-images.githubusercontent.com/17451573/31660047-6fe6f3c4-b336-11e7-9434-e0d8f900eb48.png)
  Needed adoptions:
  - [x] change (default) saving status to IN_PROGRESS
  - [x] when in DONE status, switch status button display back to IN_PROGESS after save is hit again - alternatively: display message saying "no status set" or similar.
- [ ] Editor: status changes are (in first test) carried out immediately on latest transcript version on the server belonging to the user. Status changes are not tracked. Any save activity triggers status "NEW", any status change thereafter adds another transcript on the server with the respective selected status.
  Needed adoptions (see comments for Transcriber role above):
  - [ ] ~~save activity to respect the status which is displayed by the selected status button~~
  - [x] when in DONE status, switch status button display back to IN_PROGESS after save is hit again - alternatively: display message saying "no status set" or similar.
  - [ ] make sure that EACH status change is reflected on the server (there seem to be certain inconsistencies, see below), subsidiary tests failed!
![grafik](https://user-images.githubusercontent.com/17451573/31661658-c8df8e0a-b33b-11e7-9a14-bdafa74feafc.png)
- [ ] Owner: same behavior as role Editor

Missing: 
- [ ] ~~reset status from GT to "IN_PROGRESS" after user hits the save button on a GT page~~
- [ ] clear logged tool part of commit message (applies to first action from the web interface only)

Additional feature from backend perspective
- [x] add commit message to save activity, e.g. "saved in Transkribus" or Toolname "manual, Transkribus"

**Comment by cziaarm** [comment]
@maxbry not much time, but do you think you'll be able to pick up any of @EvaMLang 's suggestions?

**Comment by cziaarm** [comment]
"when in DONE status, switch status button display back to IN_PROGESS after save is hit again - alternatively: display message saying "no status set" or similar."

@hackmanschorsch suggests this should be done server side

After saving should be able to collect the new trasncriptId and the new page status

(next iteration?)

**Comment by cziaarm** [comment]
MEssages "TRanscript saved", "page status changed" etc should timeout after a long enough period

**Comment by cziaarm** [comment]
@jnphilipp @maxbry This issue has become a bit of a monster...

My understanding is that the points in @EvaMLang 's comment that are ticked are ready to test and that those that are struck through are invalid or postponed.

That leaves a few that are neither ticked nor struck through. 

@hackmanschorsch I know that some of the issues were to be settled (at least partially) server side. I would assume that if that is the case they will need to wait for the next iteration?

**Comment by hackmanschorsch** [comment]
connected with #38:

Please check if the status of the transcript you send to the server is null!

On the server we change it either from 'NEW' to 'InProgress' or keep the old status automatically. But this works not if the status is implicitely set to 'NEW' or some other status (please check! - we do not change from any status to 'NEW' so I guess this must be set from the WebUI)

**Comment by hackmanschorsch** [comment]
issue #80: waits for deployment and uses toolname (Web Interface) during commit

@EvaMLang: At the moment on the server side we have following logic: If the status change origins from the same user as the current transcript then there is no new transcript saved. Exceptions is if it is the first transcript(=NEW). Reason is to have not too much versions. But save is always a new transcript.

don't understand: clear logged tool part of commit message??

**Comment by EvaMLang** [comment]
Server-side logic sounds fine! The issues I had before was probably session timeouts. 
The toolname should be saved (and be visible in the Job Dialog in TranskribusX).
