### ISSUE TITLE
Move image instead of dialog

### ISSUE THREAD

**Issue by kansallisarkisto** [Transkribus/TWI-edit#62]
Opening an issue to discuss the experimental change to dialog placement that was requested in the Helsinki meeting. It has now been implemented (and the change to the text font) and this issue can be used to discuss and change it.

**Comment by cziaarm** [comment]
I think this works nicely, but...

In cases where the initial line is in the corner of the image (like a page number) the edit box stays in that corner. Technically this is working fine and I think it makes sense to move the image rather than box, but I guess the corner case should be considered...

A good example of what I mean can be found here: https://transkribus.eu/readTest/edit/2305/23316/1

**Comment by GuenterMuehlberger** [comment]
I think the feature behaves exactly as expected and I like it very much :-) :-). With the fit to width etc. people can also work with page numbers as from above.

**Comment by hackmanschorsch** [comment]
Back again: Image does not move.

**Comment by cziaarm** [comment]
This was a fix that regressed by Matti's merge. This has now been undone. Please re-test

(how many more of these are there?)

**Comment by kansallisarkisto** [comment]
Solved locally, pushing soon.
