### ISSUE TITLE
Line by Line - editing issues

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#74]
Steps to reproduce: 

- Go to line by line and change to edit mode.
- If there is already some text in the line and you place the caret (with the mouse) into the middle of the text the caret goes to the beginning of this line 
- Only after clicking a second time the caret goes to the position you wanted

**Comment by kansallisarkisto** [comment]
Assigning this to myself because I'm working on the caret issue right now. Its incorrect placement seems to have something to do with the Firefox bug which causes it to disappear altogether. When it's invisible, text is still entered into the correct position but the code for obtaining the caret character offset doesn't work and hence it ends up in the wrong location when the line list is recreated. This problem is highly likely to be related IMHO.

**Comment by jnphilipp** [comment]
In line 219 of correct.html I have ```selectionData = [["{{ line|get_item:"@id" }}", 0, 0]];```, might that be the reason.

**Comment by cziaarm** [comment]
@kansallisarkisto  caret issues: #74, #20, #34 potentially can be "lived with" for this iteration and handled in subsequent iterations

**Comment by hackmanschorsch** [comment]
Seems the caret is solved in the version mc-v0.02 (24/10/2017). 
But another bug occured: Selecting a word and typing a new character (e.g. when the selected word is wrong and you want to type the right one instead of this) then some text (from the cache??) is copied after the newly typed character and you get accidental text.

**Comment by hackmanschorsch** [comment]
@cziaarm @kansallisarkisto  Think we should spend all efforts to resolve the bug from the last commit. This one causes a really bad user experience.

**Comment by kansallisarkisto** [comment]
Are there still problems related to this?
